version: 2

seeds:
  - name: mapping_time_offset_zone
    description: reference for mapping time offset to time zone
    columns:
      - name: tz_offset
        tests:
          - not_null
          - unique